# config.yml

backend:
  name: git-gateway
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Home Page'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
